Error in autoComplete multiple with new version of jqueryUi
In my application I got an error with autocomplete multiple type since I started using jqueryUI v1.10.3 and jquery v1.10.1
"
TypeError: $autocompleter.data(...) is undefined
var $source = $autocompleter.data('autocomplete').source;
"
I found in source example on http://jqueryui.com  that "ui-autocomplete" replace "autocomplete".